### ISSUE TITLE
Storybook deployment errors out

### ISSUE THREAD

**Issue by Skaidon** [streamich/react-use#2102]
https://streamich.github.io/react-use/ has the following error:

![image](https://user-images.githubusercontent.com/1096839/131922408-1cdc3d72-bfd9-43ba-8db6-7f30210cf639.png)

```
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/root/repo/node_modules/ts-loader/dist/index.js:91:41)
    at Object.loader (/root/repo/node_modules/ts-loader/dist/index.js:14:21)
Error: Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/root/repo/node_modules/ts-loader/dist/index.js:91:41)
    at Object.loader (/root/repo/node_modules/ts-loader/dist/index.js:14:21)
    at Object.756 (https://streamich.github.io/react-use/main.f03a0dc5.iframe.bundle.js:1:8384)
    at __webpack_require__ (https://streamich.github.io/react-use/runtime~main.c19c90be.iframe.bundle.js:1:1301)
    at webpackContext (https://streamich.github.io/react-use/main.f03a0dc5.iframe.bundle.js:1:7982)
    at https://streamich.github.io/react-use/main.f03a0dc5.iframe.bundle.js:1:880
    at Array.forEach (<anonymous>)
    at loadStories (https://streamich.github.io/react-use/main.f03a0dc5.iframe.bundle.js:1:845)
    at https://streamich.github.io/react-use/vendors~main.f06e85f2.iframe.bundle.js:2:376709
    at ConfigApi.configure (https://streamich.github.io/react-use/vendors~main.f06e85f2.iframe.bundle.js:2:310963)
    at Object.configure (https://streamich.github.io/react-use/vendors~main.f06e85f2.iframe.bundle.js:2:380450)
    at configure (https://streamich.github.io/react-use/vendors~main.f06e85f2.iframe.bundle.js:2:70090)
```

**Comment by The-End-Hero** [comment]
+1

**Comment by yescine** [comment]
+1

**Comment by Ray-56** [comment]
+1

**Comment by clenemt** [comment]
+1

**Comment by matobeno1** [comment]
+1

**Comment by KazimirPodolski** [comment]
@streamich 'help wanted' but the fix PR is ignored for month?

Could you please archive this repo so new people won't occasionally rely on unmantained library?

**Comment by shrutipandya3** [comment]
Is this issue still open?, if so i would like to work on this
