### ISSUE TITLE
Issue with SSR?

### ISSUE THREAD

**Issue by rfoel** [streamich/react-use#90]
I tried to use the package on next.js and it throws the following error:

```
Error: Addon "cssom" is missing the following dependencies:
 require("nano-css/addon/sh").addon(nano);
    at warnOnMissingDependencies (/Users/rafael/Code/blumpa-ssr/node_modules/nano-css/addon/__dev__/warnOnMissingDependencies.js:23:15)
    at exports.addon (/Users/rafael/Code/blumpa-ssr/node_modules/nano-css/addon/cssom.js:5:55)
    at Object.<anonymous> (/Users/rafael/Code/blumpa-ssr/node_modules/react-use/lib/useCss.js:27:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rafael/Code/blumpa-ssr/node_modules/react-use/lib/index.js:17:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by streamich** [comment]
Looks like [nano-css `cssom` addon](https://github.com/streamich/nano-css/blob/master/addon/cssom.js) does not support server side rendering. Either that addon has to detect SSR or in this lib we need to detect SSR and apply CSS differently. I guess, it's better if nano-css supports it.

**Comment by Jivings** [comment]
I'm getting this error trying to build normally. Is there a workaround?

**Comment by streamich** [comment]
Do you still get that error if you include a specific hook?

```js
import myHook from 'libreact/lib/myHook';
```

**Comment by nestarz** [comment]
same here using `import { useWindowSize } from "react-use";`

**Comment by tom2strobl** [comment]
> Do you still get that error if you include a specific hook?
> 
> ```js
> import myHook from 'react-use/lib/myHook';
> ```

Just for others like me now coming to the thread – importing a specific hook like mentioned indeed solves the issue. I was using `next` as well.

**Comment by WittBulter** [comment]
> Do you still get that error if you include a specific hook?
> 
> ```js
> import myHook from 'react-use/lib/myHook';
> ```

resolved. issue from `useCss.ts > import {create, NanoRenderer} from 'nano-css'`.
would you consider refactoring here?
